# Generated by Django 3.2.9 on 2021-11-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='following',
        ),
    ]
