# Generated by Django 3.2.9 on 2021-11-19 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0002_remove_advuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accaunt.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
