# Generated by Django 3.2.9 on 2021-11-24 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0003_advuser_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='following',
        ),
        migrations.AddField(
            model_name='advuser',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='accaunt.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
