# Generated by Django 3.2.9 on 2021-11-24 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0004_auto_20211124_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='followers',
        ),
        migrations.AddField(
            model_name='advuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accaunt.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
